[package]

name = "vorbisfile-sys"
version = "0.0.1"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
links = "vorbisfile"
build = "libvorbisfile/build.rs"

[build-dependencies.gcc]
git = "https://github.com/alexcrichton/gcc-rs"

[dependencies.ogg-sys]
git = "https://github.com/tomaka/ogg-sys"

[dependencies.vorbis-sys]
git = "https://github.com/tomaka/vorbis-sys"
